import math

from pygame.math import Vector2

WIDTH = 1280
HEIGHT = 720

FENCE_RADIUS = 300
FENCE_CENTER = Vector2(WIDTH / 4, HEIGHT / 2)

TUNNEL_POINT = Vector2(FENCE_CENTER.x + FENCE_RADIUS-15, FENCE_CENTER.y-25)
TUNNEL_SIZE = Vector2(35, 50)
TUNNEL_CENTRAL = Vector2(TUNNEL_POINT.x+35, TUNNEL_POINT.y+25)

DESTINATION_POINT = Vector2(FENCE_CENTER.x + FENCE_RADIUS+20, FENCE_CENTER.y-100)
DESTINATION_SIZE = Vector2(200, 200)

SCORE = 0

NNET_INPUTS = 7
NNET_HIDDEN = 12
NNET_OUTPUTS = 2

NORMALIZER = 2 * FENCE_RADIUS

GEN_SIZE = 300

MUTATION_WEIGHT_MODIFY_CHANCE = 0.3
MUTATION_ARRAY_MIX_PERC = 0.5
MUTATION_CUT_OFF = 0.2 # good to stay
MUTATION_BAD_TO_KEEP = 0.2 # bad to mutate
MUTATION_MODIFY_CHANCE_LIMIT = 0.4
MUTATION_BEST_TO_MUTE_PERC = 0.4
MUTATION_WEIGHT_LOW_MODIFY_CHANCE = 0.1

GEN_TIME = 10

SHOW = True

NUM_TO_SHOW = 10

def point_distance(p1,p2):
    return math.sqrt(math.pow(p1.x - p2.x, 2) + math.pow(p1.y - p2.y, 2))